USE MASTER 

IF DB_ID('QL_STK') IS NOT NULL
	DROP DATABASE QL_STK
GO
CREATE DATABASE QL_STK
GO

USE QL_STK
CREATE TABLE KHACH_HANG(
	CCCD CHAR(12), 
	HOTEN NVARCHAR(30), 
	DIACHI NVARCHAR(150)

	CONSTRAINT PK_KH
	PRIMARY KEY(CCCD)
)

CREATE TABLE SO_TIET_KIEM(
	MASO CHAR(6), 
	CCCD CHAR(12),
	NGAYMOSO DATE, 
	NGAYDONGSO DATE,
	SODU INT, 
	LOAITIETKIEM INT, 
	TRANGTHAI INT, 
	LAISUAT FLOAT, 
	SONGAYDUOCRUT INT, 
	TIENGUITOITHIEU INT

	CONSTRAINT PK_STK
	PRIMARY KEY(MASO)
)

CREATE TABLE PHIEU_GUI(
	MAPHIEUGUI CHAR(6), 
	MASO CHAR(6),
	NGAYGUI DATE, 
	SOTIEN INT

	CONSTRAINT PK_PG
	PRIMARY KEY(MAPHIEUGUI)

)

CREATE TABLE PHIEU_RUT(
	MAPHIEURUT CHAR(6), 
	MASO CHAR(6), 
	NGAYRUT DATE, 
	SOTIEN INT

	CONSTRAINT PK_PR
	PRIMARY KEY(MAPHIEURUT)
)

CREATE TABLE LOAI_TIET_KIEM(
	KYHAN INT, 
	LAISUAT FLOAT 

	CONSTRAINT PK_LTK
	PRIMARY KEY(KYHAN)
)

CREATE TABLE CONFIG_TOITHIEU(
	NGAYGUI INT, 
	SOTIENGUI INT
)

ALTER TABLE SO_TIET_KIEM
ADD
	CONSTRAINT FK_STK_KH
	FOREIGN KEY(CCCD) REFERENCES KHACH_HANG
GO

ALTER TABLE PHIEU_GUI
ADD
	CONSTRAINT FK_PG_STK
	FOREIGN KEY (MASO) REFERENCES SO_TIET_KIEM
GO

ALTER TABLE PHIEU_RUT
ADD
	CONSTRAINT FK_PR_STK
	FOREIGN KEY (MASO) REFERENCES SO_TIET_KIEM
GO






--XÓA DB Ở CHẾ ĐỘ ĐƠN NG DÙNG
--ALTER DATABASE	QL_STK SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--DROP DATABASE QL_STK

--CHẾ ĐỘ ĐA NG DÙNG
--ALTER DATABASE QL_STK SET MULTI_USER;

